  
name: A workflow for my Hello World file
on: [push, pull_request]

defaults:
  run:
    shell: bash
jobs:
  Script_Ubuntu:
    name: Running Script on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -R
          chmod +x ./scripts/main.sh 
          ./scripts/main.sh
